### ISSUE TITLE
Card orderBy is throwing a 500 error

### ISSUE THREAD

**Issue by codeunifier** [MagicTheGathering/mtg-sdk-python#37]
I haven't tested this with other models, but the Card model at least is throwing a 500 when using `orderBy`.

This is my query:
`Card.where(name=card_name).where(orderBy='name').all()`

And this is the response I'm getting:
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/mtgsdk/restclient.py", line 35, in get
    response = json.loads(urlopen(req).read().decode("utf-8"))
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by sakshamgaikwad-tech** [comment]
Hi! I was able to reproduce this behavior and wanted to share some findings that might help.

It looks like the issue is related to the "orderBy" parameter rather than the SDK usage itself.

Example query:

Card.where(name=card_name).where(orderBy='name').all()

This results in an HTTP 500 error. After testing, it appears that the SDK sends a request similar to:

https://api.magicthegathering.io/v1/cards?name=...&orderBy=name

When this URL is called directly, the API itself returns a 500 Internal Server Error, which suggests the failure is happening on the backend rather than in the client code.

Without the "orderBy" parameter, the same query works as expected.

Workaround
For now, removing "orderBy" and sorting client-side avoids the issue:

cards = Card.where(name=card_name).all()
cards = sorted(cards, key=lambda c: c.name)

Environment:

- Python 3.8 / 3.11
- MTGSDK 1.3.1
- Linux

It may be helpful to either:

- Add a note about unsupported or unstable query parameters, or
- Add graceful handling when the API returns HTTP 5xx responses.

Thanks for maintaining this project!
